# Generated by Django 5.1.3 on 2024-11-05 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='category_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='cookapp.category'),
        ),
    ]
